---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: end-of-file-fixer
      # - id: pretty-format-json
      - id: trailing-whitespace
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
